tap "beeftornado/rmtree"
tap "buo/cask-upgrade"
tap "github/bootstrap"
tap "heroku/brew"
tap "homebrew/bundle"
tap "homebrew/cask"
tap "homebrew/cask-fonts"
tap "homebrew/cask-versions"
tap "homebrew/core"
tap "homebrew/services"
tap "samcoe/docker", "git@github.com:samcoe/homebrew-docker.git"
brew "fzf"
brew "git"
brew "launch_socket_server", restart_service: true
brew "launchdns", restart_service: true
brew "mas"
brew "mysql@5.7", restart_service: true, link: true
brew "neovim"
brew "readline"
brew "postgresql", restart_service: true
brew "xz"
brew "the_silver_searcher"
brew "zsh"
brew "heroku/brew/heroku"
cask "appcleaner"
cask "dbeaver-community"
cask "docker-edge"
cask "dropbox"
cask "encryptme"
cask "font-fira-code"
cask "iterm2"
cask "java"
cask "onyx"
cask "slack"
cask "spectacle"
cask "spotify"
cask "the-unarchiver"
cask "transmission"
cask "viscosity"
cask "vlc"
cask "zoomus"
mas "1Password", id: 443987910
mas "Keynote", id: 409183694
mas "Numbers", id: 409203825
mas "Pages", id: 409201541
