tap "beeftornado/rmtree"
tap "buo/cask-upgrade"
tap "homebrew/bundle"
tap "homebrew/cask"
tap "homebrew/cask-fonts"
tap "homebrew/cask-versions"
tap "homebrew/core"
tap "homebrew/services"
brew "fzf"
brew "gh"
brew "git"
brew "gnupg"
brew "go"
brew "mas"
brew "neovim"
brew "xz"
brew "the_silver_searcher"
brew "zsh"
cask "1password"
cask "appcleaner"
cask "backblaze"
cask "dropbox"
cask "encryptme"
cask "firefox-developer-edition"
cask "font-jetbrains-mono"
cask "kitty"
cask "onyx"
cask "rectangle"
cask "spotify"
cask "the-unarchiver"
cask "transmission"
cask "vlc"
cask "zoomus"
mas "Keynote", id: 409183694
mas "Numbers", id: 409203825
mas "Pages", id: 409201541
