#!/usr/local/bin/zsh

function app_store_update {
  echo "Starting App Store Update"
  cd ~
  mas upgrade
  echo "Finished App Store Update\n\n"
}

function brew_update {
  echo "Starting Homebrew Update"
  cd ~
  brew update
  brew upgrade
  brew cleanup --force
  brew prune --force
  echo "Finished Homebrew Update\n\n"
}

function brew_cask_update {
  echo "Starting Homebrew Cask Update"
  cd ~
  brew update
  brew cu --all --yes --cleanup # https://github.com/buo/homebrew-cask-upgrade
  brew cask cleanup
  echo "Finished Homebrew Cask Update\n\n"
}

function brew_backup {
  echo "Starting Homebrew Backup"
  cd ~
  brew bundle dump --force
  echo "Finished Homebrew Backup\n\n"
}

function vim_plugins_update {
  echo "Starting Vim Plugin Update"
  cd ~
  nvim -c "PlugUpgrade | PlugUpdate | PlugClean! | qall"
  echo "Finished Vim Plugin Update\n\n"
}

function zprezto_update {
  echo "Starting Prezto Update"
  cd ~
  zprezto-update
  echo "Finished Prezto Update\n\n"
}

function commit {
  echo "Starting Server Commit"
  cd ~
  if ! config diff --quiet; then
    config commit -a -m "$(date +%F) Update"
    config push
  fi
  echo "Finished Server Commit\n\n"
}

app_store_update
brew_update
brew_cask_update
brew_backup
vim_plugins_update
zprezto_update
commit
