#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

# Customize to your needs...
alias config='/usr/bin/git --git-dir=/Users/samcoe/.cfg/ --work-tree=/Users/samcoe'
alias ghd='/Users/samcoe/github/cli/bin/ghd'

export EDITOR=/usr/local/bin/nvim
export VISUAL=/usr/local/bin/nvim
export LESSHISTFILE=/dev/null
export HISTFILE="${ZDOTDIR:-$HOME}/.zhistory"
export GOPATH="$HOME/github/go"
export GPG_TTY=$(tty)
